apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# non-kubeflow
########
- argocd-applications/sealed-secrets.yaml
- argocd-applications/metallb.yaml
# - argocd-applications/nfs-server-provisioner.yaml
# - argocd-applications/rook-ceph.yaml
# - argocd-applications/nginx.yaml
# - argocd-applications/nvidia-gpu-operator.yaml
# - argocd-applications/argocd.yaml
######
# - argocd-applications/istio.yaml
######
# to use upstream istio comment out line above
# and uncomment the next two line
# - argocd-applications/istio-upstream.yaml
# - argocd-applications/istio-operator.yaml
# kubeflow
########
# - argocd-applications/kubeflow-roles-namespaces.yaml
# - argocd-applications/cert-manager.yaml
# - argocd-applications/oidc-authservice.yaml
# - argocd-applications/dex-istio.yaml
# - argocd-applications/knative.yaml
# - argocd-applications/pipelines.yaml
# - argocd-applications/kfserving.yaml
# - argocd-applications/katib.yaml
# - argocd-applications/central-dashboard.yaml
# - argocd-applications/pod-defaults.yaml
# - argocd-applications/jupyter-web-app.yaml
# - argocd-applications/notebook-controller.yaml
# - argocd-applications/profile-controller_access-management.yaml
# - argocd-applications/tensorboard-controller.yaml
# - argocd-applications/tensorboards-web-app.yaml
# - argocd-applications/volumes-web-app.yaml
# - argocd-applications/tensorflow-operator.yaml
# - argocd-applications/pytorch-operator.yaml
# - argocd-applications/mpi-operator.yaml
# - argocd-applications/mxnet-operator.yaml
# - argocd-applications/xgboost-operator.yaml
# - argocd-applications/user-namespace.yaml
########
# - argocd-applications/experimental-pvcviewer-controller.yaml
# - argocd-applications/experimental-volumes-web-app.yaml
# Monitoring and logging
# - argocd-applications/monitoring-resources.yaml
# - argocd-applications/kube-prometheus-stack.yaml
# - argocd-applications/loki-stack.yaml
# - argocd-applications/kiali.yaml

# patchesStrategicMerge:
# - finalizer-patch.yaml
patches:
- path: finalizer-patch.yaml
  target:
    kind: Application
# patches:
# - target:
#     kind: Application
#   patch: |-
#     - op: add
#       path: /metadata/finalizers/-
#       value: resources-finalizer.argocd.argoproj.io
#     - op: replace
#       path: /spec/source/repoURL
#       value: https://github.com/cyrano5614/argoflow
# - target:
#     kind: Certificate
#     name: istio-ingressgateway-certs
#   patch: |-
#     - op: delete
#       path: /spec/commonName
#     - op: delete
#       path: /spec/dnsNames
#     - op: add
#       path: /spec/ipAddresses/-
#       value: 192.168.1.241

