apiVersion: v1
kind: ConfigMap
metadata:
  name: dex
data:
  config.yaml: |
    # issuer: http://dex.auth.svc.cluster.local:5556/dex
    issuer: https://kf.rois-theorem.com/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true
    enablePasswordDB: true
    staticPasswords:
    - email: user@kubeflow.org
      hash: $2y$12$4K/VkmDd1q1Orb3xAt82zu8gk7Ad6ReFR4LCP9UeYE90NLiN9Df72
      # https://github.com/dexidp/dex/pull/1601/commits
      # FIXME: Use hashFromEnv instead
      username: user
      userID: "15841185641784"
    staticClients:
    # https://github.com/dexidp/dex/pull/1664
    - idEnv: OIDC_CLIENT_ID
      redirectURIs: ["/login/oidc"]
      # redirectURIs: ["/login/oidc", "https://kf.rois-theorem.com/login/oidc"]
      # redirectURIs: ["/login/oidc", "https://kf.rois-theorem.com/dex/login/oidc"]
      name: 'Dex Login Application'
      secretEnv: OIDC_CLIENT_SECRET
    connectors:
    - type: github
      # Required field for connector id.
      id: github
      # Required field for connector name.
      name: GitHub
      config:
        # Credentials can be string literals or pulled from the environment.
        clientID: CLIENT_ID
        clientSecret: CLIENT_SECRETS
        # redirectURI: http://dex.auth.svc.cluster.local:5556/dex/callback
        redirectURI: CLIENT_CALLBACK
        # redirectURI: https://127.0.0.1:5556/dex/callback
        orgs:
            - name: rois-theorem
              teams:
                  - admins
        loadAllGroups: false

        # redirectURI: http://dex.auth.svc.cluster.local:5556/dex/callback
