apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kfserving
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cyrano5614/argoflow
    targetRevision: HEAD
    path: kubeflow/kfserving
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
