apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metrics-server

resources:
- https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.4.4/components.yaml

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --kubelet-insecure-tls=true
    # - op: add
    #   path: /spec/template/spec/containers/0/args/-
    #   value: --kubelet-preferred-address-types=InternalIP
  target:
    kind: Deployment

