apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../bases/kubeflow-base

patches:
- target:
    kind: Application
  patch: |-
    - op: replace
      path: /metadata/finalizers/0
      value: resources-finalizer.argocd.argoproj.io
    - op: replace
      path: /spec/source/repoURL
      value: https://github.com/cyrano5614/argoflow
- target:
    kind: Certificate
    name: istio-ingressgateway-certs
  patch: |-
    - op: delete
      path: /spec/commonName
    - op: delete
      path: /spec/dnsNames
    - op: replace
      path: /spec/ipAddresses/-
      value: 192.168.1.241

