apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ingressgateway-certs
  namespace: istio-system
spec:
  secretName: istio-ingressgateway-certs
  issuerRef:
    name: kubeflow-self-signing-issuer
    kind: ClusterIssuer
  ipAddresses:
  - 192.168.1.241
  # commonName: kubeflow.example.com
  # dnsNames:
  #   - kubeflow.example.com
