apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy
spec:
  template:
    spec:
      containers:
        - name: controller
          args:
          - --key-prefix
          - sealed-secrets-key
          - --update-status
