apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "KrbfexLUbs4v0lfhzTX+IymZUrAw9xdiIlZMTj6qT24Hl4l0E/Wf7vziySFIrJ2N\ngyPIVJhQ7PO38iRMYtUf97TOwMDXOhnSRDqr8Lqo6ECg7PSMzapecUKrBsJB0Tgx\nzxfVZ0EWvpU7CSO+qSHNkDsp3Xert1F6cB0ABpL7/Vg="
