apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "mwCGOS8n/n5/bQaN+2ijdqxcpOPHRmcQARJWecatIN5HiduW51nL17y63KW2QhM0\nPvb0K26gp/u2NbSk7bZVFJk1MVZJAUD350eBE1miEaFpY7iRLF89njxg0S/674nS\nA7MeyNaOOfntqJVI2Hko3I8d9CBQgSGUDQ3VO/P+0ps="
