apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx

resources:
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.46.0/deploy/static/provider/baremetal/deploy.yaml

patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --enable-ssl-passthrough
  target:
    kind: Deployment
    name: ingress-nginx-controller
- patch: |-
    - op: replace
      path: /spec/type
      value: LoadBalancer
    - op: add
      path: /spec/LoadBalancerIP
      value: 192.168.1.240
  target:
    kind: Service
    name: ingress-nginx-controller
